services:
  - type: web
    name: bodyiron
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: composer install && php artisan key:generate
    startCommand: php artisan serve --host=0.0.0.0 --port=80
